security:
    providers:
        in_memory: { memory: ~ }
        user_provider:
            entity:
                class:    App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   .*
            anonymous: true
            provider:  user_provider
            form_login:
                check_path:          login
                login_path:          login
                default_target_path: /
            logout:
                path:     /logout
                target:   /

    encoders:
        App\Entity\User:
            algorithm:            bcrypt
            cost:                 13
    
    role_hierarchy:
        ROLE_ADMIN:   ROLE_USER

    access_control:
        - { path: ^/(task|project), roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
