security:
    providers:
        in_memory: { memory: ~ }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true

    encoders:
        App\Entity\User:
            algorithm:            bcrypt
            cost:                 13

    access_control:
        # - { path: ^/profile, roles: ROLE_USER }
